from . import rds_template
from . import rds_template_field
from . import rds_export_log
from . import rds_dashboard
from . import rds_localization
from . import docucraft_branding
from . import rds_template_ui
from . import sale_order
from . import report_sale_document
from . import account_move
from . import report_invoice_document
from . import purchase_order
from . import report_purchase_document
from . import report_design
from . import ir_actions_report
from . import rds_report_language
from . import rds_template_version
from . import rds_template_rule
from . import rds_template_field_insight
from . import rds_health
from . import rds_retention
from . import rds_quick_export
from . import rds_export_job
