{
    "name": "Meta Lead Ads to CRM",
    "summary": "Send Facebook and Instagram Instant Form leads directly to Odoo CRM",
    "version": "19.0.1.0.0",
    "category": "Sales/CRM",
    "author": "Your Company",
    "website": "https://www.example.com",
    "support": "support@example.com",
    "license": "OPL-1",
    "price": 9.0,
    "currency": "EUR",
    "depends": ["crm", "utm", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/meta_lead_data.xml",
        "data/ir_cron.xml",
        "views/meta_connection_views.xml",
        "views/meta_routing_rule_views.xml",
        "views/meta_field_mapping_views.xml",
        "views/meta_event_views.xml",
        "views/crm_lead_views.xml",
        "wizards/meta_lead_test_wizard_views.xml",
        "views/meta_menu.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
