{
    "name": "DocuCraft – All-in-One Document Designer for Odoo",
    "summary": "PDF ve düzenlenebilir Word tasarımını satış, muhasebe, satın alma ve Studio ile birleştirir",
    "description": (
        "DocuCraft All-in-One; satış teklifleri, faturalar ve satın alma belgeleri "
        "için PDF, düzenlenebilir DOCX, PDF görünümünde DOCX, PNG ve ZIP çıktıları, "
        "tek DocuCraft Yazdır akışı, 14 kurumsal tasarım, arka plan kuyruğu, "
        "dinamik alanlar, çok şirketli şablonlar, belge dili ve Odoo Studio "
        "rapor seçicisini tek kurulumda sunar. "
        "Bu birleşik sürüm Odoo Enterprise Studio ile birlikte kurulur."
    ),
    "version": "19.0.3.1.0",
    "category": "Productivity/Documents",
    "author": "Ranvals Software",
    "website": "https://odooranvals.com",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "mail",
        "sale_management",
        "account",
        "purchase",
        "web_studio",
    ],
    "external_dependencies": {
        "python": [
            "python-docx",
            "pypdfium2",
            "Pillow",
        ],
    },
    "data": [
        "security/rds_security.xml",
        "security/rds_platform_security.xml",
        "security/rds_export_job_security.xml",
        "security/ir.model.access.csv",
        "security/rds_studio_rules.xml",
        "security/rds_language_security.xml",
        "report/rds_paperformat.xml",
        "data/rds_template_data.xml",
        "data/rds_export_job_data.xml",
        "report/rds_report_templates.xml",
        "report/report_sale_document.xml",
        "report/report_invoice_document.xml",
        "report/report_purchase_document.xml",
        "views/rds_template_views.xml",
        "views/rds_template_design_views.xml",
        "views/rds_export_log_views.xml",
        "views/rds_export_wizard_views.xml",
        "views/rds_export_job_wizard_views.xml",
        "views/rds_dashboard_views.xml",
        "views/rds_platform_views.xml",
        "views/rds_menus.xml",
        "views/rds_export_job_views.xml",
        "views/rds_platform_menus.xml",
        "views/rds_language_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/purchase_order_views.xml",
        "data/sale_server_action.xml",
        "data/account_server_action.xml",
        "data/purchase_server_action.xml",
        "views/docucraft_branding_sale.xml",
        "views/docucraft_branding_account.xml",
        "views/docucraft_branding_purchase.xml",
        "data/docucraft_branding.xml",
        "data/rds_retention_cron.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ranvals_document_studio/static/src/scss/rds_sidebar.scss",
            "ranvals_document_studio/static/src/scss/rds_views.scss",
            "ranvals_document_studio/static/src/js/rds_download.js",
            "ranvals_document_studio/static/src/js/rds_sidebar.js",
            "ranvals_document_studio/static/src/js/rds_sidebar_views.js",
            "ranvals_document_studio/static/src/js/rds_account_sidebar_views.js",
            "ranvals_document_studio/static/src/scss/rds_dashboards.scss",
            "ranvals_document_studio/static/src/js/rds_dashboards.js",
            "ranvals_document_studio/static/src/xml/rds_sidebar.xml",
            "ranvals_document_studio/static/src/xml/rds_sidebar_views.xml",
            "ranvals_document_studio/static/src/xml/rds_account_sidebar_views.xml",
            "ranvals_document_studio/static/src/xml/rds_download.xml",
            "ranvals_document_studio/static/src/xml/rds_dashboards.xml",
            "ranvals_document_studio/static/src/js/rds_motion.js",
            "ranvals_document_studio/static/src/js/rds_language_motion.js",
            "ranvals_document_studio/static/src/xml/rds_language_motion.xml",
            "ranvals_document_studio/static/src/scss/rds_language_motion.scss",
            "ranvals_document_studio/static/src/js/rds_design_fields.js",
            "ranvals_document_studio/static/src/xml/rds_design_fields.xml",
            "ranvals_document_studio/static/src/scss/rds_design_fields.scss",
            "ranvals_document_studio/static/src/xml/docucraft_branding.xml",
        ],
        # Every Studio-only file stays in Enterprise Studio's lazy bundle so
        # normal backend pages do not eagerly load the report editor extension.
        "web_studio.studio_assets_minimal": [
            "ranvals_document_studio/static/src/studio/js/selector_flow.js",
            "ranvals_document_studio/static/src/studio/js/report_design_selector.js",
            "ranvals_document_studio/static/src/studio/js/report_language.js",
            "ranvals_document_studio/static/src/studio/xml/report_design_selector.xml",
            "ranvals_document_studio/static/src/studio/xml/report_language.xml",
            "ranvals_document_studio/static/src/studio/scss/report_design_selector.scss",
        ],
        "web.assets_unit_tests": [
            "ranvals_document_studio/static/tests/**/*.test.js",
        ],
        "web.assets_web_dark": [
            "ranvals_document_studio/static/src/scss/rds_theme.dark.scss",
        ],
    },
    "icon": "/ranvals_document_studio/static/description/docucraft_app_icon_v9_20260914.png",
    "images": [
        "static/description/product_showcase.png",
        "static/description/promo_hero.png",
        "static/description/promo_features.png",
        "static/description/promo_formats.png",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
